# Redirect user to the swagger interface
api_redirect:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: "api_entrypoint"

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
